### ISSUE TITLE
Add `java,org.openrewrite.java.SpringFormat` to Spring repositories.

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/jenkins-ingest#125]
I noticed formatting on `spring-vault` is set to spaces, while the standard format is tabs.
![Screenshot 2023-07-06 at 11 20 07 AM](https://github.com/moderneinc/jenkins-ingest/assets/16889475/70765959-7b87-4a03-bf5b-2940667833d3)

I spot-checked the repos CSV, and many of the spring projects are missing the `java,org.openrewrite.java.SpringFormat` style. I wonder if the style was missed while ingest was expanded or if it was intentionally not included.

**Comment by kmccarp** [comment]
Is this still needed? @traceyyoshima @timtebeek

**Comment by timtebeek** [comment]
Looks like we stripped out explicit formatting. 
```csv
$ grep spring-vault repos.csv 
,spring-projects/spring-vault,main,,,java,,,,
```
