### ISSUE TITLE
Jenkins Validation jobs outdated

### ISSUE THREAD

**Issue by natedanner** [moderneinc/jenkins-ingest#170]
Validation jobs are using an old version of the CLI and the job needs to be reseeded. Currently the seed job is a groovy script. https://github.com/moderneinc/jenkins-ingest/blob/main/validate_seed.groovy. This should probably be an addition to mod-connect. At a minimum the groovy script should be updated to use the latest cli

[Slack Message](https://moderneinc.slack.com/archives/C02MMFD9DKJ/p1696826828194079)

**Comment by timtebeek** [comment]
Quick note here that @sghill would be interested in using the validation jobs through the API as well, and generating the validation jobs will likely happen in [the open sourced mod-connect](https://github.com/moderneinc/mod-connect/blob/main/src/main/java/io/moderne/connect/commands/Jenkins.java). Tagged here such that he can follow along, and get updates as we work, such that he does not have to implement such validation execution for followup himself.

**Comment by timtebeek** [comment]
Picked up in https://github.com/moderneinc/mod-connect/pull/51 ; now what's left is to recreate those jobs and validate that the jobs run from the SaaS.

**Comment by natedanner** [comment]
Validation recreated and jobs running again with flag ship
