### ISSUE TITLE
Ingest of Gradle projects should consider top-level projects that do not have a `build.gradle` file

### ISSUE THREAD

**Issue by tkvangorder** [moderneinc/jenkins-ingest#29]
As an example, the project https://github.com/gradle/gradle-project-templates has a `gradlew` and a `settings.gradle` file but does not have a `build.gradle` file. The `add-repo.sh` is incorrectly marking this repo as "no top level build file" and skipping it.

We should investigate if we can relax this restriction.

**Comment by okundzich** [comment]
What are the implications of this - we cannot ingest a large number of Gradle projects? Specific projects Gradle asked for etc. @tkvangorder

**Comment by tkvangorder** [comment]
I think generally, most Gradle projects have a `build.gradle` file at the top level. I do not think it is common to see a project like this, but I think I would want @sambsnyd or @jkschneider to weigh in here.

**Comment by sambsnyd** [comment]
add-repo.sh should be augmented to check for the presence of of build.gradle.kts, settings.gradle, or settings.gradle.kts
