### ISSUE TITLE
Capture Failures when ingesting projects into the public SaaS

### ISSUE THREAD

**Issue by tkvangorder** [moderneinc/jenkins-ingest#3]
Currently, each repository has a generated Jenkins ingest job and any failure of the job requires us to manually open the failed build and then examine logs. It would be much better to aggregate build failures and a common suggestion has been to use Gradle Enterprise.

The current workflow has a single Jenkins job that generates each nested ingest job dynamically from a CSV. This means that the Gradle enterprise plugin must be dynamically injected into each of these ingest jobs. This will be done differently depending on the version of Gradle and when the project is a maven project.

- [ ] Add code to dynamically inject the Gradle Enterprise plugin to each ingest job
- [ ] Add better discovery detection to set the build tool version

**Comment by okundzich** [comment]
Also see https://github.com/moderneinc/moderne-scm/issues/174 @tkvangorder 
Please merge these two issues and keep up to date with our progress/new issues etc.

**Comment by tkvangorder** [comment]
This has been completed, both Maven and Gradle builds are now being collected in Gradle Enterprise.
