### ISSUE TITLE
Add new OSS GitHub Action broken

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/jenkins-ingest#97]
While trying to add some organizations such as PicnicSupermarket, codehaus-plexus & arquillian I found the GitHub Action is currently [broken in Checkout already](https://github.com/moderneinc/jenkins-ingest/blob/main/.github/workflows/addGitHubOrganization.yaml#L16):
https://github.com/moderneinc/jenkins-ingest/actions/runs/5043563863/jobs/9045502733

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +28ef06ec4f8c62563a63a3ea9c45be237929830e:refs/remotes/origin/main
  Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
```

**Comment by timtebeek** [comment]
Seeing similar reports here: https://github.com/actions/checkout/issues/664

**Comment by rpau** [comment]
We need a token for this and probably this one of my Moderne tokens that has expired.

**Comment by rpau** [comment]
It seems that is fixed now.
